### ISSUE TITLE
Fastboot support?

### ISSUE THREAD

**Issue by chbonser** [leizhao4/ember-webcam#12]
Does this addon support fastboot?  I've tried using it with Ember 2.14 and ember-cli-fastboot 1.0.5.  The app loads only if I disable fastboot.  Otherwise I get the following error.

```
ReferenceError: location is not defined
    at .../tmp/broccoli_merge_trees-output_path-HnNS9VbB.tmp/assets/vendor/webcamjs/webcam.js:41:1
    at .../tmp/broccoli_merge_trees-output_path-HnNS9VbB.tmp/assets/vendor/webcamjs/webcam.js:1040:1
    at .../tmp/broccoli_merge_trees-output_path-HnNS9VbB.tmp/assets/vendor.js:66723:3
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at VMSandbox.eval (.../node_modules/fastboot/src/vm-sandbox.js:14:16)
    at .../node_modules/fastboot/src/ember-app.js:136:15
    at Array.forEach (native)
    at EmberApp.loadAppFiles (.../node_modules/fastboot/src/ember-app.js:133:21)
....
```

**Comment by leizhao4** [comment]
Hi @chbonser! Unfortunately no, I didn't create this addon with FastBoot compatibility in mind. It's shouldn't be too hard to fix, but I can't work on this project right now. If someone can submit a PR, that would be great.

I would also love to transfer ownership if someone wants to take it over.

**Comment by chbonser** [comment]
I'd be happy to take over if you want to transfer.

**Comment by leizhao4** [comment]
@chbonser Awesome! I'm transferring the repo and the NPM package to you.

**Comment by leizhao4** [comment]
@chbonser You might also want to update the broken URLs in README.md and package.json. 😄

**Comment by chbonser** [comment]
Thanks @leizhao4. I'll be giving this some attention today.
