### ISSUE TITLE
Babel 5-to-6 deprecations

### ISSUE THREAD

**Issue by nikdojo** [leizhao4/ember-webcam#16]
Hi!

Could you please update the addon to remove babel 5-->6 deprecation warnings, please?
Thx.

**Comment by chbonser** [comment]
@nikdojo Thanks for the reminder. I'll try to carve out time in the next couple of weeks.

**Comment by chbonser** [comment]
I've upgraded ember and cleaned up dependencies. This removes the deprecations.  See version 0.1.0
