### ISSUE TITLE
App using addon crashes, cannot find module ember-resolver, emver-cli-version-checker

### ISSUE THREAD

**Issue by andreiciceu** [leizhao4/ember-webcam#6]
Hello,

Our app was using this addon for taking pictures from camera.

With the new version of ember-cli (2.11.1), the app builds fine, but crashes, with the following errors in the browser's Javascript console: **Cannot find module at `require('ember-resolver')` and `require('ember-cli-version-checker')`**.
I've tried including those packages in **package.json**, but no luck

EmberJS: 2.9.0
Ember-cli: 2.11.1
Node: 6.10.0
Npm: 3.10.10

**Comment by leizhao4** [comment]
Thank you @andreiciceu! I've never seen these error messages before, but I'll try if I can replicate them.

**Comment by leizhao4** [comment]
Hi @andreiciceu, sorry I couldn't reproduce your issue. I created a new app using your configs (Ember 2.9.0, Ember CLI 2.11.1) and added ember-webcam to it. It works fine. I'm wondering if your issue was caused by something else.

Would you please share the full error message? Also if you don't mind share the content of your `package.json` file, I might be able to help you find the cause.

Also, did you upgrade Ember CLI from 2.9.0 to 2.11.1? Make sure you follow the steps in the [release note](https://github.com/ember-cli/ember-cli/releases/tag/v2.11.1). Missing the `ember init` step often causes problems.

Hope it helps!

**Comment by andreiciceu** [comment]
@leizhao4 sure, here are the contents of package.json
I've tried with the latest CLI and with a new project, still, the error appears
```
{
  "name": "dd",
  "version": "0.0.0",
  "description": "Small description for dd goes here",
  "license": "MIT",
  "author": "",
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "repository": "",
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.5",
    "ember-ajax": "^2.4.1",
    "ember-async-button": "1.0.2",
    "ember-browserify": "1.1.13",
    "ember-cli": "2.11.1",
    "ember-cli-app-version": "^2.0.0",
    "ember-cli-babel": "^5.1.7",
    "ember-cli-bootstrap-datepicker": "0.5.6",
    "ember-cli-bootstrap-sassy": "0.5.5",
    "ember-cli-chart": "3.1.0",
    "ember-cli-dependency-checker": "^1.3.0",
    "ember-cli-document-title": "0.3.3",
    "ember-cli-dropzonejs": "0.9.4",
    "ember-cli-htmlbars": "^1.1.1",
    "ember-cli-htmlbars-inline-precompile": "^0.3.6",
    "ember-cli-if-component": "0.4.2",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-jshint": "^2.0.1",
    "ember-cli-loading-slider": "^1.3.1",
    "ember-cli-qunit": "^3.0.1",
    "ember-cli-release": "^0.2.9",
    "ember-cli-sass": "6.1.1",
    "ember-cli-shims": "^1.0.2",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-test-loader": "^1.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-cli-version-checker": "^1.2.0",
    "ember-click-outside": "0.1.6",
    "ember-cookies": "0.0.13",
    "ember-data": "^2.11.0",
    "ember-export-application-global": "^1.0.5",
    "ember-form-for": "2.0.0-alpha.13",
    "ember-i18n": "5.0.0",
    "ember-load-initializers": "^0.6.0",
    "ember-modal-dialog": "0.9.1",
    "ember-moment": "7.3.0",
    "ember-power-select": "1.6.0",
    "ember-resolver": "^2.0.3",
    "ember-route-action-helper": "2.0.2",
    "ember-simple-auth": "1.2.0",
    "ember-sortable": "1.9.3",
    "ember-webcam": "0.0.2",
    "loader.js": "^4.0.10",
    "webcamjs": "1.0.22"
  },
  "engines": {
    "node": ">= 0.12.0"
  },
  "private": true,
  "dependencies": {
    "chart.js": "^2.5.0",
    "webcamjs": "^1.0.22"
  }
}
```

Error message:
![image](https://cloud.githubusercontent.com/assets/9255607/24093088/bea1ad88-0d5a-11e7-92ac-e0fac7f79abc.png)

**Comment by leizhao4** [comment]
@andreiciceu Thanks a lot for the information! I think I have a potential solution now. I'll release a new version if it works out.

**Comment by leizhao4** [comment]
@andreiciceu Please try version 0.0.3 and see if the problem still exists.

**Comment by andreiciceu** [comment]
@leizhao4 Seems to be working now. Thank you

**Comment by leizhao4** [comment]
Sweet! Thank you for help @andreiciceu!
